parameters:

services:
  _defaults:
    autowire: true
    autoconfigure: true

  # Enregistre automatiquement les classes de src/
  App\:
    resource: '../src/'
    exclude:
      - '../src/DependencyInjection/'
      - '../src/Entity/'
      - '../src/Kernel.php'

  # Déclaration explicite (optionnelle, car déjà couverte par App\:)
  App\Service\Importer\ParticipantCsvImporter: ~
